version: "3.1"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: ./.env
    environment:
      "MYSQL_DB": "${DB_DATABASE}"
      "MYSQL_USERNAME": "${DB_USERNAME}"
      "MYSQL_PASSWORD": "${DB_PASSWORD}"
      "HOSTNAME": "${DB_HOSTNAME}"
  app:
    image: node:10
    container_name: my-app
    links:
      - mysql
    ports:
      - "${APP_PORT}"
    env_file: ./.env
    environment:
      "PORT": "${APP_PORT}"
