swagger: "2.0"
info:
  version: "0.0.1"
  title: Units controller backend
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /create:
    x-swagger-router-controller: unit_controller
    get:
      description: Creating new unit
      operationId: create
      parameters:
        - name: path
          in: query
          description: Main module for the new element 
          required: false
          type: string
        - name: content
          in: query
          description: New item content
          required: false
          type: string
      responses:
        "200":
          description: A User object
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /change:
     x-swagger-router-controller: unit_controller
     get:
      description: Change this unit
      operationId: change
      parameters:
        - name: id
          in: query
          description: Main module for the new element 
          required: false
          type: string
        - name: content
          in: query
          description: Change item content
          required: false
          type: string
      responses:
        "200":
          description: A User object
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /remove:
    x-swagger-router-controller: unit_controller
    get:
      description: Remove this unit
      operationId: remove
      parameters:
        - name: ids
          in: query
          description: Determines the serial number of the unit
          required: false
          type: string
      responses:
        "200":
          description: A User object
          schema:
            type: object
        default:
          description: Error
          schema:
             type: object                              
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
