swagger: "2.0"
info:
  version: 1.0.4
  title: Units controller backend
host: localhost:10010
basePath: /
schemes:
  - https
  - http
paths:
  /api/elements:
    x-swagger-router-controller: unit_controller
    get:
      description: Get all parameters
      operationId: all
      responses:
        "200":
          description: A User object
          schema:
            type: object
        default:
          description: Error
  /api/element:
    x-swagger-router-controller: unit_controller
    post:
      description: Creating new unit
      operationId: create
      parameters:
        - $ref: '#/parameters/DefaultResponse'
        - $ref: '#/parameters/CreateResponse'
      responses:
        '200':
          $ref: '#/responses/DefaultResponse'
        '404':
          $ref: '#/responses/ElementNotFound'
    put:
      description: Change this unit
      operationId: change
      parameters:
        - $ref: '#/parameters/DefaultResponse'
        - $ref: '#/parameters/ChangeResponse'
      responses:
        '200':
          $ref: '#/responses/DefaultResponse'
        '404':
          $ref: '#/responses/ElementNotFound'
    delete:
      description: Remove this unit
      operationId: remove
      parameters:
        - $ref: '#/parameters/RemoveResponse'
      responses:
        '200':
          $ref: '#/responses/DefaultResponse'
        '404':
          $ref: '#/responses/ElementNotFound'
responses:
  ElementNotFound:
    description: Element not found
  DefaultResponse:
    description: Return object data

parameters:
  DefaultResponse:
    name: content
    in: query
    description: Change item content
    type: string
    required: true
  CreateResponse:
    name: path
    in: query
    description: Main module for the new element
    type: string
    required: true
  ChangeResponse:
    name: id
    in: query
    description: Main module for the new element
    type: string
    required: true
  RemoveResponse:
    name: ids
    in: query
    description: Determines the serial number of the unit
    type: string
    required: true
