swagger:
  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers 
  bagpipes:
    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]
    _swagger_validate:
      name: swagger_validator
      validateResponse: true
    swagger_controllers:
      - cors
      - swagger_security      
      - _swagger_validate      
      - _router
    swagger_raw:
      name: swagger_raw
